### PR TITLE
Added a new method of sharing your builds.

### LINKED ISSUE #38: share.sh doesn't handle multiple remotes well

### PR DESCRIPTION
**Pull request by ehgoodenough**
## Context

We've been having a lot of trouble with uploading our builds, especially recently. I've switched to using [gh-pages](https://www.npmjs.com/package/gh-pages) to handle the uploading process.

Closes #38.
## Selfie

selfie-0

### CODE REVIEW

**Comment by ehgoodenough** [comment]
At the moment, the build is named by it's version number, but we should add a method for allowing us to name the build something like "music" or "monster" or whatever. Maybe use a randomized identifier instead of version number, to decrease any duplicate build names?

**Comment by Willamin** [comment]
I didn't see this PR before I did #58, but after looking at this PR, it seems that the named builds feature could be extracted from #58 and used with this PR. That could even be extended to use a randomized url key.

**Review by Willamin — COMMENTED** [review]
Does `node share` need to be added to the scripts listing in package.json?

**Comment by Willamin** [comment]
After running, I get the following. Presumably, it all works and it just won't succeed because there would be duplicated tags. Other than that, this LGTM 👍 

```
$ node share
Cloning git@github.com:mocsarcade/enchiridion.git into node_modules/gh-pages/.cache
Cleaning
Fetching origin
Checking out origin/gh-pages
Copying files
Adding all
Committing
Tagging
Tagging failed, continuing
{ ProcessError: fatal: tag 'v1.0.0' already exists

    at ChildProcess.<anonymous> (/Users/will/Documents/dev/enchiridion/node_modules/gh-pages/lib/git.js:47:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  code: 128,
  message: 'fatal: tag \'v1.0.0\' already exists\n',
  name: 'ProcessError' }
Pushing
```

**Comment by ehgoodenough** [comment]
Yeah, I left in the logging for now, but I'm not happy with what it's logging :\

**Pull request closed without merging**
