### PR TITLE
Add electron build script

### PR DESCRIPTION
**Pull request by Willamin**
Running the following commands will add executables for Windows, Mac, and Linux for both 32-bit and 64-bit to the `builds/electron` directory.

```
$ npm install
$ node build
$ node electronify
```

### CODE REVIEW

**Comment by ehgoodenough** [comment]
Good progress! It runs in an electron app? That's fantastic!

**Comment by ehgoodenough** [comment]
@Willamin: Would you consider documenting your script for packaging in the `package.json`:

https://github.com/mocsarcade/enchiridion/blob/master/package.json

**Comment by Willamin** [comment]
@ehgoodenough ready for review

**Review by ehgoodenough — APPROVED** [review]
Fantastic work!!

**Pull request merged**
