### PR TITLE
Rendered hearts in the HUD.

### PR DESCRIPTION
**Pull request by ehgoodenough**
## Context

I'm (finally) adding health and death to the game, so it'll actually play like a game. Players must be able to see their health at all times, so I've added hearts to the HUD to display your health. You have 3 hearts, and if it's a non-integer value, it'll render it as a heart.
## Screenshot

3v2
## Link

https://mocsarcade.github.io/enchiridion/hearts
## Selfie

selfie-0

### CODE REVIEW

**Comment by ehgoodenough** [comment]
At the moment, there isn't any death. But at least there is health!

**Comment by Willamin** [comment]
I don't see hearts on https://mocsarcade.github.io/enchiridion/hearts :(

**Comment by jcpirtle** [comment]
https://mocsarcade.github.io/enchiridion/hearts/ try this link

**Comment by jcpirtle** [comment]
Also lgtm

**Comment by jcpirtle** [comment]
Revoke my LGTM, I didn't see the hearts on the playable build

**Comment by ehgoodenough** [comment]
Updated the playable build. @jcpirtle @Willamin

**Review by Willamin — APPROVED** [review]
LGTM 👍

**Pull request merged**
