### PR TITLE
Change the structure of the monster json to include images

### PR DESCRIPTION
**Pull request by Willamin**
This will allow us to more quickly create prototypical monsters in the future.

### CODE REVIEW

**Comment by ehgoodenough** [comment]
Hey, let's rename `get sprite` to a proper getSprite function, so we don't have to name it `this.spritename`. Juuuust so we can keep it consistent.

**Comment by ehgoodenough** [comment]
Other than that, it's looking good! I love nice small changes. Please get your teammates to look over it.

**Comment by Willamin** [comment]
@ehgoodenough It looks like in `Entity.js` everything is called using the `get whatever` form instead of `getWhatever()`. I'm with you- I like consistency. In this instance, do you have a preference for whether we want `Entity.js` or `Monster.js` to be consistent?

edit: err... that's not quite right. I think I read what Entity was doing incorrectly. 

edit 2: hmmm. It looks like the `get sprite` might be required for our `get style` to work correctly with React. I might be missing something though

**Comment by ehgoodenough** [comment]
I'm fine with editing Entity to use getSprite, but what I like about the ECMA2015 getters is that we aren't assuming that it has to be a function (like we do if we use getSprite) instead allowing either a literal or a getter function.

**Comment by ehgoodenough** [comment]
The issue here is that you can't have a getter function and an instance variable with the same name. So we have to change one or the other.

**Comment by ehgoodenough** [comment]
What if we did something like:

``` js
class Monster {
    constructor(protomonster) {
        this.protomonster = protomonster
    }
    get sprite() {
        return this.protomonster.sprite
    }
}
```

**Comment by ehgoodenough** [comment]
This is weird, since we're keeping the original prototype within the new object, but whatever, it let's us namespace the data away from the sugary getters and setters.

Not sure if I like this. :\

**Comment by ehgoodenough** [comment]
The best solution is to simply drop the getter function, and make that just an instance variable on the entity that we change when the state changes.

``` js
class Monster {
    constructor(protomonster) {
        this.sprite = protomonster.sprite
    }
    // Call it a day.
}
```

**Comment by ehgoodenough** [comment]
@brandonhutchins @tpayne1 @jcpirtle Why haven't any of you looked at this yet? I can't merge it until one of you approves the changes.

**Comment by jcpirtle** [comment]
LGTM

**Comment by ehgoodenough** [comment]
Drop the getter function, and it'll LGTM :]

**Comment by jcpirtle** [comment]
Looks good to me. Andrew, Can this be merged?

**Pull request merged**
